os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
  include:

  - name: "tests"
    script:
    - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh
  - name: "quality"
    script:
    - ./scripts/genenv.sh
    - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/coverage.sh
    #- docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
    email: false
